import { Command } from "../../common/Command";
import { group_bootstrap } from "./group_bootstrap";
import { group_build } from "./group_build";
import { group_clear } from "./group_clear";
import { group_refresh } from "./group_refresh";
import { group_install } from "./group_install";
import { group_link } from "./group_link";
import { group_publish } from "./group_publish";
import { group_test } from "./group_test";
import { group_lint } from "./group_lint";
import { group_lint_fix } from "./group_lint_fix";
import { group_typecheck } from "./group_typecheck";
import { group_validate_prettiness } from "./group_validate_prettiness";
import { group_validate } from "./group_validate";
import { group_make_prettier } from "./group_make_prettier";

export const group = new Command("group");

group.addCommand(group_bootstrap);
group.addCommand(group_clear);
group.addCommand(group_install);
group.addCommand(group_link);
group.addCommand(group_lint);
group.addCommand(group_lint_fix);
group.addCommand(group_typecheck);
group.addCommand(group_validate_prettiness);
group.addCommand(group_validate);
group.addCommand(group_make_prettier);
group.addCommand(group_build);
group.addCommand(group_test);
group.addCommand(group_publish);
group.addCommand(group_refresh);
